/* DELETE 'lettersoupdb' database*/
DROP SCHEMA IF EXISTS lettersoupdb;
/* DELETE USER 'sd' AT LOCAL SERVER*/
DROP USER IF EXISTS 'sd'@'%';



/* CREATE 'lettersoupdb' DATABASE */
CREATE SCHEMA lettersoupdb;
/* CREATE THE USER 'sd' AT LOCAL SERVER WITH PASSWORD 'sd' */
CREATE USER IF NOT EXISTS 'sd'@'%' IDENTIFIED BY 'sd';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'sd' AT LOCAL SERVER*/
GRANT ALL ON lettersoupdb.* TO 'sd'@'%';

